# -*- coding: utf-8 -*-
"""M22MA003_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OW4JaEV0Xn-XqFxbTWa6t3O_TQIZ0YTF
"""

!pip install easyocr

import cv2
import easyocr
import numpy as np
import math
import matplotlib.pyplot as plt
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize']=8,16

reader = easyocr.Reader(['en'])
Image("india-map.jpg")

output = reader.readtext('india-map.jpg')
output

#  import re
#  regex = re.compile('[@_!#$%^&*()<>?/\|}{~:]')
states_list=["Andhra Pradesh","Arunachal Pradesh ","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Andaman and Nicobar Islands","Chandigarh","Dadra and Nagar Haveli","Daman and Diu","Lakshadweep","National Capital Territory of Delhi","Puducherry"]
rows = len(output)
listall=[]
for i in range(len(output)): 
      if (output[i][1]).isupper() and not(any(chr.isdigit() for chr in output[i][1])):
        centre_y_cord = 0
        centre_x_cord = 0
        for j in range(4):
          centre_x_cord += int(output[i][0][j][0])
          centre_y_cord += int(output[i][0][j][1])
        listall.append((output[i][1], int(centre_x_cord/4), int(centre_y_cord/4)))
arr = np.array(listall)
arr

def distance(arr,state1,state2):
  arr_len = len(arr)
  x1,x2,y1,y2 = 0,0,0,0
  for i in range(arr_len):
    if arr[i][0] == state1:
      x1=int(arr[i][1])
      y1=int(arr[i][2])
    if arr[i][0] == state2:
      x2=int(arr[i][1])
      y2=int(arr[i][2])
  print(f"x1,y1,x2,y2 are {x1,y1,x2,y2}")
  print("Manhatten Distance between BIHAR and GUJARAT")
  print(f"X distance is {abs(x1-x2)} and Y distance is {abs(y1-y2)}")
  print("Euclidean Distance between BIHAR and GUJARAT")
  print(f"{math.sqrt((x1-x2)**2 + (y1-y2)**2):.2f}")

distance(arr,'BIHAR','GUJARAT')

