# -*- coding: utf-8 -*-
"""M22MA003_Q10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lHGnW09s1s3ihtjlN5-ENxBVZ2riiKil
"""

!pip install easyocr

import matplotlib.pyplot as plt
import cv2
import numpy as np
import easyocr
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize'] =8,16
from google.colab.patches import cv2_imshow

import easyocr
reader = easyocr.Reader(['en'])

image1 = cv2.imread('Screenshot 2023-01-08 at 5.14.24 PM.png',0)
output1 = reader.readtext('Screenshot 2023-01-08 at 5.14.24 PM.png')
cv2_imshow(image1)
print(f"Last three digits are : {int(output1[0][1][-3:])}")

image2 = cv2.imread('Screenshot 2023-01-08 at 5.14.47 PM.png',0)
output2 = reader.readtext('Screenshot 2023-01-08 at 5.14.47 PM.png')
cv2_imshow(image2)
print(type(output2[0][1]))
print(f"Last three digits are : {int(output2[0][1][-3:])}")

