# -*- coding: utf-8 -*-
"""M22MA003_Q9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwc5S82hxjF3JlNz_vMFGNnjwckKTyOF
"""

import matplotlib.pyplot as plt
import cv2
import numpy as np
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize'] =7,9
from google.colab.patches import cv2_imshow

# img = cv2.imread('Beaver_Lake_Montreal.jpg', cv2.IMREAD_GRAYSCALE)
# assert img is not None, "file could not be read, check with os.path.exists()"
# hist = cv2.calcHist([img],[0],None,[256],[0,256])
img = cv2.imread('/content/Beaver_Lake_Montreal.jpg',1)
histogram, bin_edges = np.histogram(img, bins=10, range=(0, 255))
print(f"BinEdges are {bin_edges}")
plt.figure()
plt.title("Grayscale Histogram")
plt.xlabel("grayscale value")
plt.ylabel("pixel count")
plt.xlim([0.0, 255.0])  # <- named arguments do not work here

plt.plot(bin_edges[0:-1], histogram)
# plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

color = ('b','g','r')
# for i,col in enumerate(color):
#     print(f"i is {i} and col is {col}")
#     histr = cv2.calcHist([img],[i],None,[256],[0,256])
#     plt.plot(histr,color = col)
#     plt.xlim([0,256])
# plt.show()
img = cv2.imread('/content/Beaver_Lake_Montreal.jpg',0)
img_2 = cv2.equalizeHist(img)
res = np.hstack((img, img_2))
cv2_imshow(res)
# plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(res, cv2.COLOR_BGR2RGB))





